# -*- coding: utf-8 -*-
"""signal-tamrin2-MelFrequencyCepsralCoefficient

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nj_ZhGTBsay7TrC-opp-skavIqU6Ktg3
"""

!pip install scipy
!pip install python_speech_features
import scipy
from python_speech_features import mfcc
from python_speech_features import logfbank
import scipy.io.wavfile as wav
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
plt.rcParams["figure.figsize"] = [14,4]

(rate,sig) = wav.read("aa.wav")
mfcc_feat_aa = mfcc(sig,rate)

ig, ax = plt.subplots()
mfcc_data_aa= np.swapaxes(mfcc_feat_aa, 0 ,1)
cax = ax.imshow(mfcc_data_aa, interpolation='nearest', cmap=cm.coolwarm, origin='lower', aspect='auto')
ax.set_title('MFCC data')
#Showing mfcc_data
plt.show()
#Showing mfcc_feat

ax.set_title('MFCC coefficient aa')
plt.plot(mfcc_feat_aa)
plt.show()

import scipy
from python_speech_features import mfcc
from python_speech_features import logfbank
import scipy.io.wavfile as wav
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
plt.rcParams["figure.figsize"] = [14,4]

(rate,sig) = wav.read("e.wav")
mfcc_feat_e = mfcc(sig,rate)

ig, ax = plt.subplots()
mfcc_data_e= np.swapaxes(mfcc_feat_e, 0 ,1)
cax = ax.imshow(mfcc_data_e, interpolation='nearest', cmap=cm.coolwarm, origin='lower', aspect='auto')
ax.set_title('MFCC data')
#Showing mfcc_data
plt.show()
#Showing mfcc_feat
ax.set_title('MFCC coefficient e')
plt.plot(mfcc_feat_e)
plt.show()

import scipy
from python_speech_features import mfcc
from python_speech_features import logfbank
import scipy.io.wavfile as wav
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
plt.rcParams["figure.figsize"] = [14,4]

(rate,sig) = wav.read("ee.wav")
mfcc_feat_ee = mfcc(sig,rate)

ig, ax = plt.subplots()
mfcc_data_ee= np.swapaxes(mfcc_feat_ee, 0 ,1)
cax = ax.imshow(mfcc_data_ee, interpolation='nearest', cmap=cm.coolwarm, origin='lower', aspect='auto')
ax.set_title('MFCC data')
#Showing mfcc_data
plt.show()
#Showing mfcc_feat
ax.set_title('MFCC coefficient ee')
plt.plot(mfcc_feat_ee)
plt.show()

import scipy
from python_speech_features import mfcc
from python_speech_features import logfbank
import scipy.io.wavfile as wav
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
plt.rcParams["figure.figsize"] = [14,4]

(rate,sig) = wav.read("o.wav")
mfcc_feat_o = mfcc(sig,rate)

ig, ax = plt.subplots()
mfcc_data_o= np.swapaxes(mfcc_feat_o, 0 ,1)
cax = ax.imshow(mfcc_data_o, interpolation='nearest', cmap=cm.coolwarm, origin='lower', aspect='auto')
ax.set_title('MFCC data')
#Showing mfcc_data
plt.show()
#Showing mfcc_feat
ax.set_title('MFCC coefficient o')
plt.plot(mfcc_feat_o)
plt.show()

import scipy
from python_speech_features import mfcc
from python_speech_features import logfbank
import scipy.io.wavfile as wav
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
plt.rcParams["figure.figsize"] = [14,4]

(rate,sig) = wav.read("u.wav")
mfcc_feat_u = mfcc(sig,rate)

ig, ax = plt.subplots()
mfcc_data_u= np.swapaxes(mfcc_feat_u, 0 ,1)
cax = ax.imshow(mfcc_data_u, interpolation='nearest', cmap=cm.coolwarm, origin='lower', aspect='auto')
ax.set_title('MFCC data')
#Showing mfcc_data
plt.show()
#Showing mfcc_feat
ax.set_title('MFCC coefficient o')
plt.plot(mfcc_feat_u)
plt.show()